# Netlify Configuration for Adaptive Book Hygiene React App
# =========================================================

[build]
  # Build command - install dependencies and build
  command = "npm ci && npm run build"
  
  # Directory to publish (Vite outputs to 'dist' by default)
  publish = "dist"
  
  # Enable form detection and ignore admin directory
  ignore = "/admin/"
  
  # Node.js version for build environment
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"
    # Build optimizations
    GENERATE_SOURCEMAP = "false"
    VITE_BUILD_ANALYZE = "false"
    NODE_ENV = "production"
    # Ensure environment variables are available during build
    NPM_CONFIG_PRODUCTION = "false"

# Static Asset Handling (MUST come before SPA routing)
# ====================================================
# Prevent static assets from being caught by SPA routing
# These rules ensure assets are served directly with proper MIME types

# Serve static assets directly - no redirects for these paths
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200
  force = false

[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200
  force = false

[[redirects]]
  from = "/*.woff2"
  to = "/:splat.woff2"
  status = 200
  force = false

[[redirects]]
  from = "/*.ico"
  to = "/:splat.ico"
  status = 200
  force = false

[[redirects]]
  from = "/*.png"
  to = "/:splat.png"
  status = 200
  force = false

[[redirects]]
  from = "/*.jpg"
  to = "/:splat.jpg"
  status = 200
  force = false

[[redirects]]
  from = "/*.svg"
  to = "/:splat.svg"
  status = 200
  force = false

[[redirects]]
  from = "/*.json"
  to = "/:splat.json"
  status = 200
  force = false

# SPA Routing Configuration (MUST come after static asset rules)
# ==============================================================
# OAuth Callback specific handling
[[redirects]]
  from = "/oauth-callback"
  to = "/index.html"
  status = 200
  force = false

# Catch-all redirect for client-side routing (React Router)
# This MUST be the LAST redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security Headers
# ================
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking attacks
    X-Frame-Options = "DENY"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Enable XSS protection
    X-XSS-Protection = "1; mode=block"
    
    # Control referrer information
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Permissions policy for enhanced security
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Static Asset Optimization & MIME Type Safety
# =============================================
[[headers]]
  for = "/static/*"
  [headers.values]
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache Vite assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    # Explicit MIME type for JavaScript files
    Content-Type = "application/javascript; charset=utf-8"
    # Cache JavaScript files
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.mjs"
  [headers.values]
    # Explicit MIME type for ES modules
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    # Explicit MIME type for CSS files
    Content-Type = "text/css; charset=utf-8"
    # Cache CSS files
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    # Explicit MIME type for font files
    Content-Type = "font/woff2"
    # Cache font files
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Content-Type = "font/ttf"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Content-Type = "image/x-icon"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.map"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# TypeScript source files (fallback safety - should not be served in production)
[[headers]]
  for = "*.ts"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "*.tsx"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"

# ES Module files
[[headers]]
  for = "*.esm.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# HTML files - shorter cache for SPA updates
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# API Integration Security
# ========================
# Allow connections to required external services
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy for QBO, Clerk, and Supabase integration
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.clerk.com https://clerk.com https://*.clerk.accounts.dev;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' 
        https://api.clerk.com 
        https://*.clerk.accounts.dev 
        https://lwdjpwkrvafwrlizcroj.supabase.co 
        https://n8n-1-102-1-c1zi.onrender.com 
        https://appcenter.intuit.com;
      frame-src 'self' https://*.clerk.accounts.dev https://js.clerk.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """

# Build Processing Optimization
# =============================
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true
  
[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true


# Functions Configuration (Future Use)
# ====================================
[functions]
  # Directory for Netlify Functions (if needed later)
  directory = "netlify/functions"
  
# Forms Configuration (if contact forms are added)
# ================================================
# Form detection is configured in the main [build] section above
  
# Branch Deploy Configuration
# ===========================
# Production deployment from main branch only
[context.production]
  environment = { NODE_ENV = "production" }
  
# Branch deployments disabled per requirements
[context.branch-deploy]
  command = "echo 'Branch deploys disabled'"
  
# Deploy previews disabled per requirements  
[context.deploy-preview]
  command = "echo 'Deploy previews disabled'"